name: 'load UWLCM Apptainer image'
description: 'set env var SI to point to the image location'
inputs:
  path:
    description: 'Where to put the image'
    required: true
  tag:
    description: 'Image tag'
    required: true
    default: 'uwlcm_ubuntu_24_04_cuda_12_9_0'

runs:
  using: "composite"
  steps:
  
  - name: Install Apptainer
    #when installed from this action, .SIF is always converted to sandbox (could be related to: https://githubmemory.com/repo/hpcng/singularity/issues/6065)
    uses: eWaterCycle/setup-apptainer@v2
    with:
      apptainer-version: 3.8.3
    #apt installation following https://sylabs.io/guides/3.0/user-guide/installation.html, but this is a too old version and uninstalls python-is-python3
#    run: |
#      wget -O- http://neuro.debian.net/lists/focal.de-fzj.libre | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
#      sudo apt-key adv --recv-keys --keyserver hkps://keyserver.ubuntu.com 0xA5D32F012649A5A9
#      sudo apt-get update
#      sudo apt-get install -y singularity-container
          
  - name: Cache UWLCM Apptainer image
    id: cache_apptainer
    uses: actions/cache@v4
    with:
      path: '${{ inputs.path }}/uwlcm_${{ inputs.tag }}.sif'
      key: '${{ inputs.tag }}'
      
  - name: Download UWLCM Apptainer image
    shell: bash
#    if: steps.cache_singularity.outputs.cache-hit != 'true'
    run: |
      [ "${{steps.cache_apptainer.outputs.cache-hit}}" != "true" ] && \
      {
      mkdir '${{ inputs.path }}';
      wget --no-verbose -P '${{ inputs.path }}' https://zenodo.org/records/15591478/files/${{ inputs.tag }}.sif
      } \
      || \
      true
    # disable Apptainer cache, we cache manually

  - name: Set friendly Apptainer image name
    uses: allenevans/set-env@v2.0.0
    with:
      SI: '${{ inputs.path }}/${{ inputs.tag }}.sif'
